server:
  port: 8080
spring:
  application:
    name: spring-boot
  datasource:
    url: jdbc:h2:mem:db-spring
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: warn
    com.asy.test.springboot: debug