# currently not working via yaml file
#quarkus:
#  http:
#    port: 8081
#  datasource:
#    db-kind: h2
#    username: sa
#    password: password
#    jdbc:
#      url: jdbc:h2:mem:db-spring
#  hibernate-orm:
#    database:
#      generation: update
#  log:
#    level:
#      ROOT: WARN
#      com.asy.test.quarkus: DEBUG
